language: perl6
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libreadline5-dev
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda installdeps .
  - panda installdeps .
